---
- name: Configure Linux VM
  hosts: ansible_host
  become: yes
  tasks:
    - name: Update package cache
      yum:
        name: "*"
        state: latest
    - name: Install Apache
      yum:
        name: httpd
        state: present
    - name: Start Apache service
      service:
        name: httpd
        state: started
        enabled: yes
