version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing Terraform..."
      - curl -fsSL https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip -o terraform.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - terraform --version
  build:
    commands:
      - echo "Initializing Terraform..."
      - terraform init
      - echo "Applying Terraform configuration..."
      - terraform apply -auto-approve
  post_build:
    commands:
      - echo "Terraform deployment completed."
      - echo "VM Public IP $(terraform output -raw vm_public_ip)"
artifacts:
  files:
    - "**/*"
