---
version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing Terraform..."
      - curl -fsSL
        https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
        -o terraform.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - terraform --version
  build:
    commands:
      - echo "Initializing Terraform..."
      - terraform init
      - echo "Applying Terraform configuration..."
      - terraform apply -auto-approve
  post_build:
    commands:
      - echo "Terraform deployment completed. VM IP $(terraform output -raw
        vm_public_ip)"
      - vmip=$(terraform output -raw vm_public_ip) 
      - export vmip
      - |
        curl -X POST -H "Authorization: Bearer EXavlnvpStVS18fMr943Bc4WrSJcsW" \
        -H "Content-Type: application/json" \
        -d "{\"inventory\": 2, \"extra_vars\": {\"ansible_host\": \"$vmip\"}}" \
        http://13.233.92.247:30000/api/v2/job_templates/9/launch/
artifacts:
  files:
    - "**/*"
